<?php
//----------------------------------------------------------------------------------------------------------------------
namespace SetBased\Audit\Test\MySql;

use SetBased\Audit\MySql\Command\AuditCommand;
use SetBased\Stratum\MySql\StaticDataLayer;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Tester\CommandTester;
use Symfony\Component\Process\Process;

//----------------------------------------------------------------------------------------------------------------------
/**
 * Tests for table locking.
 */
class LockTableTestCase extends AuditTestCase
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Connects to the MySQL server.
   */
  public static function setUpBeforeClass()
  {
    parent::setUpBeforeClass();
    
    StaticDataLayer::multiQuery(file_get_contents(__DIR__.'/LockTableCase/setup.sql'));
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Test locking table is in verbose output.
   */
  public function test01()
  {
    $application = new Application();
    $application->add(new AuditCommand());

    /** @var AuditCommand $command */
    $command = $application->find('audit');
    $command->setRewriteConfigFile(false);
    $commandTester = new CommandTester($command);
    $commandTester->execute(['command'     => $command->getName(),
                             'config file' => 'test/MySql/LockTableTestCase/audit.json'],
                            ['verbosity' =>
                               OutputInterface::VERBOSITY_NORMAL |
                               OutputInterface::VERBOSITY_VERBOSE |
                               OutputInterface::VERBOSITY_VERY_VERBOSE]);

    $status = $commandTester->getStatusCode();
    $this->assertSame(0, $status, 'status code');

    $output = $commandTester->getDisplay();
    $this->assertContains('lock tables `TABLE1` write', $output, 'acquire');
    $this->assertContains('unlock tables', $output, 'release');
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Test that the table is actually locked.
   */
  public function test02()
  {
    $application = new Application();
    $application->add(new AuditCommand());

    // Start process that inserts rows into TABLE1.
    $generator = new Process(__DIR__.'/LockTableCase/generator.php');
    $generator->start();

    // Give generator some time to startup.
    sleep(2);

    /** @var AuditCommand $command */
    $command = $application->find('audit');
    $command->setRewriteConfigFile(false);
    $commandTester = new CommandTester($command);
    $commandTester->execute(['command'     => $command->getName(),
                             'config file' => 'test/MySql/LockTableTestCase/audit.json']);

    // Tell the generator it is time to stop.
    $generator->signal(SIGUSR1);

    $status = $commandTester->getStatusCode();
    $this->assertSame(0, $status, 'status code');

    $generator->wait();

    // Reconnect to DB.
    StaticDataLayer::connect('localhost', 'test', 'test', self::$dataSchema);

    // It can take some time before that all rows generated by $generator are visible by this process.
    $n1 = 0;
    $n2 = 0;
    sleep(5);
    for ($i = 0; $i<60; $i++)
    {
      $n1 = StaticDataLayer::executeSingleton1("select AUTO_INCREMENT - 1 
                                                from information_schema.TABLES
                                                where TABLE_SCHEMA = 'test_data'
                                                and   TABLE_NAME   = 'TABLE1'");
      $n2 = StaticDataLayer::executeSingleton1('select count(*) from test_audit.TABLE1');

      if (4 * $n1==$n2) break;

      sleep(3);
    }

    $this->assertEquals(4 * $n1, $n2, 'count');
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
